# Generated by Django 3.2.9 on 2021-12-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.URLField(max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='publicado/no Publicado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odsApp.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odsApp.categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
