# Generated by Django 3.2.9 on 2021-12-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsApp', '0004_alter_post_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombres',
            field=models.CharField(max_length=90, verbose_name='Nombres autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
